import { beforeEach, describe, expect, it, vi } from "vitest";
import { useFakeScanStore } from "@/testing/fake-scan-store";
import { SCAN_ID, VALID_SCAN_BODY } from "@/testing/scan-route-requests";
import { spyOnServerLog } from "@/testing/server-log-spy";
import { STUB_WORKER_URL, stubWorker } from "@/testing/stub-worker";
import { startScan } from "./start-scan";

vi.mock("@/server/db/scan-store", () => ({ getScanStore: vi.fn() }));

const START = { request: VALID_SCAN_BODY, clientId: "203.0.113.7" };

describe("startScan", () => {
	const store = useFakeScanStore();

	beforeEach(() => {
		vi.spyOn(crypto, "randomUUID").mockReturnValue(SCAN_ID);
		spyOnServerLog();
	});

	it("stores the running scan before calling the worker", async () => {
		// GIVEN
		const order: string[] = [];
		store().createRunning.mockImplementation(() => {
			order.push("store");
			return Promise.resolve();
		});
		const calls = stubWorker(201, { scanId: SCAN_ID });

		// WHEN
		await startScan(START);

		// THEN
		expect([...order, ...calls.map(({ url }) => url)]).toEqual([
			"store",
			`${STUB_WORKER_URL}/scans`,
		]);
	});

	it("sends the generated scan id to the worker", async () => {
		// GIVEN
		const calls = stubWorker(201, { scanId: SCAN_ID });

		// WHEN
		await startScan(START);

		// THEN
		expect(calls[0]?.body).toEqual({ scanId: SCAN_ID, ...VALID_SCAN_BODY });
	});

	it("answers 201 with the scan id generated by web", async () => {
		// GIVEN
		stubWorker(201, { scanId: "worker-echo" });

		// WHEN
		const response = await startScan(START);

		// THEN
		expect({ status: response.status, body: await response.json() }).toEqual({
			status: 201,
			body: { scanId: SCAN_ID },
		});
	});

	it.each([
		[409, "SCAN_ALREADY_RUNNING"],
		[422, "URL_NOT_ALLOWED"],
		[502, "WORKER_UNAVAILABLE"],
		[503, "CAPACITY_REACHED"],
	] as const)(
		"discards the row when the worker answers %d",
		async (status, code) => {
			// GIVEN
			stubWorker(status, { error: { code, message: "From the worker." } });

			// WHEN
			await startScan(START);

			// THEN
			expect(store().discard).toHaveBeenCalledWith(SCAN_ID);
		},
	);

	it("relays the worker's rejection unchanged", async () => {
		// GIVEN
		const workerBody = {
			error: { code: "CAPACITY_REACHED", message: "Busy." },
		};
		stubWorker(503, workerBody);

		// WHEN
		const response = await startScan(START);

		// THEN
		expect({ status: response.status, body: await response.json() }).toEqual({
			status: 503,
			body: workerBody,
		});
	});
});
